services:
  - type: web
    name: bucket-stress-test
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: BUCKET_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: FILE_SIZE_BYTES
        value: "1932735283"
      - key: TG_BOT_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
